Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent  = true
  config.ssh.insert_key     = false # we'll use the insecure key by default on this system

  config.vm.define :leo do |node|
    node.vm.network :private_network, ip: "10.1.1.10"

    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
    end

    node.vm.provision "ansible" do |ansible|
      # ansible.verbose = "vvvv"
      ansible.playbook = "playbook-vagrant.yml"
    end
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :
