---
  - name: add jenkins apt keys
    apt_key:
      url: "{{ item }}"
    with_items: "{{ apt_keys }}"

  - name: add jenkins apt repositories
    apt_repository:
      repo: "{{ item }}"
    with_items: "{{ apt_repositories }}"

  - name: accept oracle license
    debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: apt-get update
    apt: update_cache=yes

  - name : install jenkins packages
    apt: name="{{ item }}"  state=latest
    with_items: "{{ apt_packages }}"
