---
  - name: apt-get update
    apt: update_cache=yes

  - name: apt-get upgrade
    apt: upgrade=yes

  - name: install common package(s)
    apt: name="{{ item }}" state=latest
    with_items: "{{ apt_packages }}"
